name = "TeXmath"
uuid = "6a08ed6d-59f2-481e-a137-9a2a2f38f1bf"
authors = ["Carlos André Bohn Brandt <andre@cbrandt.com.br>"]
version = "0.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
